name: NUMERO #

on: [push] # Cuando hagas push

jobs: 
  ci: #prueba 1
    runs-on: ubuntu-latest #arranca maquina ubuntu

    steps: # haz esto
      - uses: actions/checkout@v2
      - name: PHPUnit Tests
        uses: php-actions/phpunit@v1
        env:
          TEST_NAME: numeroTest # nombre del test
        with:
          configuration: test/phpunit.xml #mirar que se llame igual y que esté dentro de la carpeta test
          args: --coverage-text
  cd: #prueba 2
    runs-on: ubuntu-latest #hace un ubuntu
    needs: ci

    steps:
      - uses: actions/checkout@v1
      - name: Docker Login #logea en dockerhub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }} 
      - name: Build
        run: | #construye un container
          docker build -t ${{ secrets.DOCKER_USER }}/numerocicd:${{ github.sha }} . 
          docker build -t ${{ secrets.DOCKER_USER }}/numerocicd:latest . 
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/numerocicd:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/numerocicd:latest    